# Setup
title:               Titanium Blog
tagline:             'Не блог, а заметки'
description:         'Не блог, а заметки'
url:                 https://titanrain.org
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              TheTitanRain
  url:
  email:

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.1.0
google_analytics_id: #UA-XXXX-Y
#